server:
  port: 8081
spring:
  application:
    name: itemservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heima?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.138.128
    port: 6379
    password: 123456
mybatis-plus:
  type-aliases-package: com.heima.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.heima: debug
  pattern:
    dateformat: HH:mm:ss:SSS